.catalog:
  name: Jenkins
  version: 2.3
  description: |
    Jenkins CI management server.
  questions:
    - variable: "PORTMAPPING"
      label: "Portmapping to expose "
      type: "string"
      required: true
      description: The ports to map
      default: "8080:8080"
    - variable: "plugins"
      type: "multiline"
      label: "List of Plugins"
      description: |
        List of plugins in the format <plugin_name>[:<version>]
        one entry per line.
      default: |
        credentials
        greenballs
        git
        junit
        git-client
        github-api
        github-oauth
        github
        plain-credentials
        scm-api
        ssh-credentials
        ssh-slaves
        swarm
jenkins-primary:
  metadata:
    plugins: |
      ${plugins}
